import { PrismaClient } from '@prisma/client'
import { randomUUID } from 'crypto'

const prisma = new PrismaClient()

async function main() {
  await prisma.$transaction([
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email1',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email2',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email3',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email3',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email4',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email5',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Frontend',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email6',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Frontend',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email7',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Frontend',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email8',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email9',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email10',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email11',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email12',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email13',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'UI/UX',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email14',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email15',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email16',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email17',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email18',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email19',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email20',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email21',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor WordPress',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email22',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Flutter Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email23',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Flutter Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email24',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer UI',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email25',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer UI',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email26',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer UI',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email27',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer UI',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email28',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer UI',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email29',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer gráfico',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email30',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer gráfico',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email31',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer gráfico',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email32',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Designer gráfico',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email34',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Analista de Inovação Digital',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email35',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Dev Web JR',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email36',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Gerente de sucesso do cliente',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email37',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Gerente de sucesso do cliente',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email39',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Graphic Designer/Production',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email40',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Web Designer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email41',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Web Designer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email42',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Web Designer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email43',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Web Designer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email44',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor Full Stack',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email45',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor Full Stack',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email46',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor Full Stack',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email47',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Desenvolvedor Full Stack',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email48',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Full Stack Software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email49',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Full Stack Software Developer',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
    prisma.user.create({
      data: {
        id: randomUUID(),
        role: 'user',
        email: randomUUID(),
        password: 'abcdefghijklmnopq',
        username: 'email50',
        curriculum: {
          create: {
            id: randomUUID(),
            civil_state: 'civil_state',
            first_name: 'first_name',
            last_name: 'last_name',
            phone: 'phone',
            presentation: 'presentation',
            public_email: randomUUID(),
            slug: randomUUID(),
            title: 'Software Developer Full Stack ',
            contact_preference: 'whatsapp',
          },
        },
      },
    }),
  ])
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
